### PR TITLE
Renaming Modular components and Shells to Tenants

### PR DESCRIPTION
**Pull request by Jetski5822**
Bunch of renaming

Shell -> Tenant

Orchard.Environment.Extensions* -> OrchardCore.Extensions*
Orchard.Environment.Shell* -> OrchardCore.Tenant*
Microsoft.AspNetCore.Modules -> OrchardCore.Modules
Microsoft.AspNetCore.Mvc.Modules -> OrchardCore.Mvc.Modules

### CODE REVIEW

**Comment by Jetski5822** [comment]
@Piedone @DanielStolt what do you boi's think of the renaming??

**Comment by agriffard** [comment]
@Jetski5822 Will you also rename all modules and themes?

BTW, I tried it on an existing instance and it is launching the Setup.
I guess I will have to restart from the ground.

**Comment by DanielStolt** [comment]
I don't disagree with Shell -> Tenant. But I do think the Environment namespace has some value.

**Comment by Jetski5822** [comment]
@agriffard yeah after this PR has been merged in

**Comment by PinpointTownes** [comment]
@Jetski5822 question: can we wait until the OpenID PR is merged?

**Comment by Jetski5822** [comment]
@PinpointTownes totally man

**Comment by Jetski5822** [comment]
@DanielStolt I like the Environment thing too, as I introduced it. But Not sure its good if these are going to be public nuget packages..... let me have a think

**Comment by PinpointTownes** [comment]
> @PinpointTownes totally man

Thanks! @jersiovic's PR is already huge enough ; good to know we can avoid a new merge commit 😄

**Comment by Piedone** [comment]
Thanks for asking @Jetski5822 .

My issue with the shell -> tenant rename is that it's a slightly different concept:

- A tenant is a logical unit, a sub-site. This notion is interesting for users.
- A shell is a concrete container that encompasses services of Orchard and is scoped to a tenant, i.e. you create a shell for a tenant. (And this notion is only interesting for developers.)

However you can create multiple shells for the same tenant: This is possible even in a single application, but if you run your app on two servers then you'll also need to have two shells, but for the same, one tenant. You can have a shell without a tenant (at least in O1, we actually use it routinely: https://github.com/Lombiq/Orchard-Application-Host-Sample/blob/master/Samples/TransientHostSample.cs) and you can have a tenant without a shell (i.e. have all the data for the tenant but it not running; this happens also when the tenant is disabled).

As for the Environment question I also see value in keeping the namespace, but I know too little about the current state of the project to be sure.

**Comment by sebastienros** [comment]
Three options, not exclusive:
- I am too tired
- I need to review my Domain Design lessons
- You are wrong

And to add confusion you say that you can create multiple shells for the same tenant, and nick tells on the chat the opposite ;)

It's not because you can instantiate two objects representing the same concept that you need another name for the class and the concept. That why we have `.Equals()` and `==`.
We have an `Extension` class, it will be duplicated in as many nodes, and yet it represent an extension, OMG, mind blown ;)

**Comment by DanielStolt** [comment]
What @Piedone is saying is exactly what I said to @sebastienros on Skype. This conceptual distinction between a tenant and a shell is what I was referring to, but Zoltan expresses in much more elegantly here.

**Comment by Jetski5822** [comment]
Closing and removing this branch for now. Will redo later.

**Pull request closed without merging**
