### PR TITLE
Merge Master into Users

### PR DESCRIPTION
**Pull request by rserj**

### CODE REVIEW

**Comment by Jetski5822** [comment]
Hey @rserj this doesnt look right?

**Comment by rserj** [comment]
I would like to merge "users" branch into "master" branch, but I got a conflict, so I decided to merge "master" into "users" by resolving conflicts, before merging "users" to "master". 
I made merge locally "master" into "users" and created a pull request.

**Comment by Jetski5822** [comment]
@sebastienros ^^^^

**Comment by sebastienros** [comment]
Merging should not add all these commits, in the end it should just be one ...
I can try to rebase if it helps

**Comment by rserj** [comment]
No rebase, I'll make it differently. Do not accept this PR, thanks

**Pull request closed without merging**
