### PR TITLE
Update the aspnet-contrib/OpenIddict packages

### PR DESCRIPTION
**Pull request by PinpointTownes**

### CODE REVIEW

**Comment by sebastienros** [comment]
Meh, now I have to copy the packages on our myget feed. You give me so much work!

**Comment by PinpointTownes** [comment]
> Meh, now I have to copy the packages on our myget feed. You give me so much work!

Why? This repository references the aspnet-contrib feed in `NuGet.config`, so there's no work needed to use these packages during build.

Now, if you want the Orchard feed to be the only external feed people have to register to use Orchard and all its modules, packages mirroring is likely the best option: http://docs.myget.org/docs/how-to/make-myget-list-and-automatically-mirror-packages-from-other-feeds

**Comment by sebastienros** [comment]
Yes, for the modular support I copy the packages. I looked into mirroring but I just want to mirror what is not in nuget.org.

Now I see this:

> However using the package proxy feature, search results and packages from upstream sources can be automatically mirrored to your feed.

So apparently I could configure our feed to proxy all the other ones we require, that would be perfect.

**Comment by PinpointTownes** [comment]
image

Obviously, something went wrong... :trollface:

**Comment by sebastienros** [comment]
Do you mean I missed a package? Because I haven't done the proxy thing yet.

**Comment by PinpointTownes** [comment]
You did (if you take a look at the screenshot, you'll see you ended up with inconsistent versions, as the 1.0.0 version of the extensions package is missing).

You should consider removing all the non-Orchard packages from the orchardcore-preview feed and mirror the feeds you need.

BTW, I regenerated the 1.0.0 packages earlier today, so the binaries you have on your feed are not exactly the same as the ones that will be uploaded to NuGet.org later this feed.

**Comment by sebastienros** [comment]
> I regenerated the 1.0.0 packages 

Are you an evil person?

**Comment by PinpointTownes** [comment]
I am! Should I join you at MSFT, then? 'cause you guys do the same thing with the ASP.NET packages :trollface:

**Comment by sebastienros** [comment]
Remember the Orchard and ASP.NET project are managed in a completely different way. We are way more evil than ASP.NET sometimes, but usually not.

**Comment by sebastienros** [comment]
I configured the proxy feeds, it worked on my machine, we'll see how it goes, thanks for the tip.

**Comment by PinpointTownes** [comment]
Nice :+1:

**Pull request merged**
