### PR TITLE
ShapeTable caching

### LINKED ISSUE #140: Reuse IShapeTableManager across tenants
From my tests by trying to start 1000 tenants this is the most consuming part in terms of startup perf and memory. It can easily be changed to store each theme's `ShapeTable` at the application level, but each module can provide different bindings (some attribute binding could override a template one).

The solution is to create a ShapeTable per feature and whenever a binding is looked up then just use the ones that are enabled.
However not all features/modules add some attribute bindings, and themes always win and don't vary by tenant. We could then look in the Theme bindings first, then module ones, by adding a priority or a chain of responsibility instead of merging all the bindings. Each tenant could have its own chain of responsability, and reuse all the bindings for each feature.

For instance:

Tenant 1:
ThemeA -> Module 1 -> Module 2 (shape found)

Tenant2 (without Module 1)
ThemeA -> Module 2 (shape found)

The features are chained using feature priority order (as today).

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #140.
Work in progress, just to save it.
Started on ShapeAlterations caching.
Best.

### CODE REVIEW

**Comment by jtkech** [comment]
**Done**

- First, there are 2 kinds of `IShapeTableProvider`, one which provides `ShapeAlterations` from itself and one which provide `ShapeAlterations` harvested from others currently enabled features. So, to make the difference we use a new `IShapeTableHarvester` which only inherit from `IShapeTableProvider`.

- Here, when using binding strategies (shapes providers), we call only once `IShapeTableProviders` and pass to `IShapeTableHarvesters` a list of features to exclude when creating `ShapeAlterations`.

- To do this,  each `ShapeAlteration` is cached with a key based on the type of the current strategy (`IShapeTableProvider `), the `Feature` related to the alteration, and the `ShapeType`.

**Todo**

- Then, through `ShapeAlterations` we create `ShapeDescriptors` to build a `ShapeTable`. So, see how we can cache `ShapeDescriptors` and also update and re-order their binding collections

**Tests**

- Right now, the shape table is 1st built in 100 ms, then by using cached alterations rebuilt in 15 ms.

- About memory, because we don't yet cache everithing, we still use `IMemoryCache` (one per tenant).

Best.

**Comment by jtkech** [comment]
- **1)** Through shape table providers we build **shape alterations**, this is the more consuming work, around **80ms**. Here they are cached in a static dictionary and we build only the new ones. In testing, when they are re-used for a shape table of a new theme, this part now takes around **6ms**.

- **2)** Then we use **shape alterations** (now cached) to configure **shape descriptors** by initializing their handlers and bindings collections. **This is here that shapes are binded to features** and where we could change things to index **feature miniShape tables** cached at the application level.

- But let see if it is worth to do this because, whatever the way we use, in **2)** we need to do something when the context changes (e.g the theme). And not sure it could be faster (see below).

- So, after some improvements part **2.** takes around **13ms** in a first pass, then around **5ms** when re-building a table for a new theme. Notice that half of the time is to re-order things by dependencies.

- **3.** So, if you think we can still use a **Memory cache** per tenant to store its shape tables, i think we are ok because we would only have to take into account the shape table creation where all the consuming work of part **1.** for creating shape alterations is now cached at the application level.

- If not, same question but with a local dictionary. here we would need to use a `Scoped` lifetime for the shape table manager. Note: a shape table currently consumes about **22 Kbytes**.

- If we can't cache shape tables per themes and per tenant, a first idea i've tested is to cache the keys order of their related shape alterations (less memory) not to have to re-order things by dependencies. This way, if the cache exists we can skip part **1.** and part **2.** takes only **1ms or 2ms**.

- But the shape table is frequently requested, so ... Right now, part **2.** is quite fast but can be cached only by caching all the shape table.

So, i'll wait your feedback before changing more in depth shape classes and bindings as discussed. This because if the size of the memory cache per tenant is not a concern, maybe we are already ok.

Best.

**Comment by sebastienros** [comment]
The goal here is to reuse shape tables across tenants to reduce memory consumption, not load time. It's not bad to have it load faster, but the impacting factor here is definitely memory as each tenant recreates the full structure for each of the tenants. And sure, if one module changes, or the list of the active ones, then the shape table chain is still rebuilt, reusing or not reusing any previous cached shape table.

**Comment by jtkech** [comment]
Ok, and i think i can keep part of what I've already done. Anyway, i needed to first understand how shape tables are currently built.

**Comment by sebastienros** [comment]
I am on skype, sent you a message

**Comment by jtkech** [comment]
Good progress. So, i try to use smaller objects through a class which acts as a shape descriptor but which in fact indexes (through integer keys) other mini descriptors already altered and cached.

E.g a property which is an array of action is replaced with something like this.

    get { return _alterationKeys.Select(key => _descriptors[key]).SelectMany(x => x.Displaying); }

Seems to work. Just one problem with the `BoundAs()` delegate, just found why but need to find a solution. The problem is when Altering a shape descriptor, this delegate holds a reference on it. So, when executing it will not be aware of our new pseudo descriptor (which is an indexer) which effectively uses it.

Wow, just found a solution that seems to work, need to refactor all of this ...

I think we will not need to cache shape alterations, only the generated mini shape descriptors.

**Comment by jtkech** [comment]
So, the `ShapeTable` has 2 properties.

- `Descriptors`: They now are `ShapeDescriptorIndex` which point to their related `ShapeDescriptor`

- `Bindings`: A class which now resolves the requested `ShapeBinding` from the above collection.

`ShapeTable` now consumes `9600 bytes`, first built in `112 ms`, then re-built in `10 ms`.

Best.

**Comment by sebastienros** [comment]
Question is how much more does it take for each new tenant ... and how much it was taking before the changes. Also we need to look at allocations, for 1000 requests how much memory was allocated before and now.

**Comment by jtkech** [comment]
You're right, first i was assuming that changing the theme could be the same as changing the tenant (if the same other features are enabled). I don't remember how shape table was taking before, need to retrieve it.

Then, i'll test it for a new tenant but right now don't now how to test 1000 tenants / requests ...

**Comment by sebastienros** [comment]
You are also right in saying that just switching theme would have created different tables by the past good point. For the multi-tenancy checks, you will need to restart the app after each new tenant, there is a bug right now in master that I fixed in the SaaS branch.

**Comment by jtkech** [comment]
Not so easy to compute memory sizeswith references of references ... So, not sure of the results.

Previous ShapeTable

- Descriptors: Size around 8 500 bytes, Inclusive size around 60 000 bytes.
- Bindings: Size around 4 000 bytes, Inclusive size around 60 000 bytes.
- Total: Size 12 500, Inclusive size 120 000 bytes.
- Because Bindings reference existing Descriptors, maybe **Total size = 64 000 bytes**.

New shapeTable

- Descriptors Indexes: Size around 9 500 bytes, Inclusive size around 25 000 bytes.
- Bindings: There are now resolved from the above.
- Total: Size 9 500, Inclusive size 25 000 bytes.
- Because Descriptors index cached ones, maybe **Total size = 9 500 bytes**.

Best.

**Comment by jtkech** [comment]
My bad, because of a breakpoint i was not directly seing in the `ShapeTable`, this to take all into account.

So, here the results when a new theme is requested, i think it's the same when a new tenant (with a given theme) is requested (i'll try it tomorrow).

- Previous ShapeTable: **180 000 bytes**.

- New shapeTable: **30 000 bytes**.

But not sure of the inclusive sizes, will re-do some tests tomorrow by checking the total amount of memory.

Best.

**Comment by sebastienros** [comment]
You need to use some tools to analyze the memory, you should try Jetbrains dotmemory, it's free for testing. It gives you a table of all object types, and you can compare snapshot at different phases of the system, like after creating a new tenant.

By the way the tenants/module management should be without any glitch now on the master branch.

**Comment by jtkech** [comment]
Ok, i'll try it asap, thanks. I'm finishing to test some use cases ...

**Comment by sebastienros** [comment]
Perf measuring is not a priority, just a validation step. To be satisfied with the gains. So no issues so far, still on track? Don't forget I have skype opened all the time ;)

**Comment by jtkech** [comment]
Ok, no worries, but just found something important which i'm closed to well understand.

**Comment by jtkech** [comment]
I found what was disturbing me, new objects was created and referenced by the ShapeTable.

Descriptors and their bindings are pre-altered (for all enabled themes) and cached in a static dictionary. But the ShapeTable use derived ShapeDescriptorIndex, so bindings need to be new objects which reference the right actual descriptors objects (e.g when used for displaying).

- That's why the inclusive size of the ShapeTable was growing by referencing these new objects.

- The 1st current solution was not to put Bindings in the ShapeTable and resolve the collection (of these new objects) on the fly with a little penalty on perf.

- The right solution is to use and pre-resolve the ShapeTable Bindings but with those from the static dictionary descriptors, then when requested just return a new binding with the right descriptor.

I'll do some little refactoring and re-try it.

**Comment by jtkech** [comment]
As said i was only disturbed by inclusive sizes, but finally memory diff of VS diagnostic tools seems ok.

So, my new tests seems to confirm that each time we create and cache a `ShapeTable`:

- Before: Shape tables memory grows up by around **180 000 bytes**.
- With this PR: Shape tables memory grows up by around **30 000 bytes**.

I'll test it with new tenants but i need to rebase on the master branch.

Note: We will also need to adapt unit tests code.

Best.

**Comment by jtkech** [comment]
Just for infos

- Just rebased on master, then it fails.
- Seen the new `Orchard.Commons` module ;) so maybe need a new Setup.
- Did a new Setup with an empty db prefix, then it fails again.
- Did the same but with a non empty prefix, then it's OK.

Best.

**Comment by jtkech** [comment]
Tried with a new tenant

- So, 2 tenants and 3 themes, so 6 ShapeTable.
- First table creation in around 110 ms.
- Create a new table for a new tenant in 25 ms.
- Create a new table for the same tenant but for a new theme in 10 ms.
- (Table providers and alterations are only executed for new needed features).
- On each table creation, memory of ShapeTable objects grows up by 33 000 bytes (in place of 180 000).

Best.

**Comment by sebastienros** [comment]
That's great, thanks a lot. Have you tested that module dependencies correctly define the order of alterations, and that enabling/disabling features actually impacts the rendering without interfering with other tenants?

**Comment by jtkech** [comment]
Will try it this w-end.

Which feature could i easily enable / disable for testing?

**Comment by jtkech** [comment]
Just for infos

So, when selecting a new theme in a tenant, it doesn't affect other tenants.

Now i want to enable / disable a feature which act on rendering. First tried by disabling Orchard.Navigation but all crashed. 

So now the idea is to create a sub feature of Orchard.Demo which will define a Shape or a TagHelper ... So, i first try to use: `http://localhost:2918/orchard.demo/home/DisplayShape/1` but it fails.

Maybe because of my PR, but tried it on the master branch and it also failed. In `LowerKebabToPascalCase` I needed to replace `return ""` with `return result.ToString()`. I didn't see tag helper rendering but at least it prevents from failing and the `Foo` shape is rendered.

Do you know a feature i could easily enable / disable for testing?

Best

**Comment by jtkech** [comment]
Last tests.

- So, i've used `http://localhost:2918/orchard.demo/home/DisplayShape/1` to display the `Foo` shape.

- Then i created a `Demo2` module with a higher priority and which provide the same `Foo` shape type.

- Then, `Foo` rendering is overriden but only in the tenant it is enabled.

- If `Demo2` has not a higher priority, then `Foo` rendering is never overriden.

- So seems ok, shape alterations are applied according to the enabled features and their priority.

Note:  The `Baz` tag helper was failing, in `LowerKebabToPascalCase()` I needed to replace `return ""` with `return result.ToString()`. Still not working (parameter are not passed) but at least without exception.

**Comment by sebastienros** [comment]
Sounds good.

I am merging it in a local branch right now (shapetable) to take a look and fix things if I find issues.

**Comment by sebastienros** [comment]
Can you try to fix the unit tests without ignoring any, that would be a good thing for confidence, they are currently failing due to the refactoring. Ideally we should have the same set of tests as in O1. We need to be sure that anything we touch in this layer doesn't break.

**Comment by sebastienros** [comment]
So far the perf hasn;t been impacted, I didn't see any significant perf improvement in throughput either. So all good. No trying to see how many tenants I can start on my machine with the recent changes from ASP.NET 1.1.0 too.

**Comment by jtkech** [comment]
Sorry, forgot to say that unit tests was broken with the new shape table structure. I was planning to fix it.

It also depends on your test results because i don't know how it could behave e.g when many requests  build simultaneously same alterations and descriptors for the static dictionary, maybe good to use some lock ...

**Comment by jtkech** [comment]
Just began to check unit tests. First  failing on `IfeatureManager.GetEnabledFeaturesAsync()` which is now used but not yet implemented in the tests ... Now **36 tests of 60 are passed**, i will continue tomorrow.

One thing is that some tests act on the shape table descriptors which are now descriptors indexers which point (each one) on other cached and already altered "mini" descriptors.

Just seen that the `DefautPlacement` property of a descriptor could be changed after the creation of the shape table (only in tests in O2, but seen in O1). So, a descriptor indexer which act as an aggregate also need some "global" properties which can be altered afterwards. I fixed it for the `DefautPlacement`.

Just seen that some tests add bindings to the shape table, after its creation. Here bindings are also some kind of indexes which exposes a dictionary interface which right now is read only. So, here also it seems that we have to implement the same kind of "global" properties we can update afterwards.

Let me know your test results if they are good (or bad). As said previously maybe we might need to do something when many simultaneous requests want to built the same shape table.

Best.

**Comment by jtkech** [comment]
@sebastienros Just for info i fixed unit tests, see #319 on the shapetable branch.
Currently there is a problem on Appveyor but tests on Travis are successful.

**Pull request merged**
