### PR TITLE
Dynamic compilation: implement specific compilation and runtime assets.

### PR DESCRIPTION
**Pull request by jtkech**
@Jetski5822 just as a complement to fit the following scenario.

- For most of "regular" packages dependencies, the compile time and runtime assemblies are the same. And there are no specific assemblies for different targeted runtimes.

- For many "framework" packages, the compile time assembly is not the same, and specific runtime assemblies are provided for different runtimes. When you do a `dotnet publish`, these assemblies are populated in the `refs` and `runtimes` subfolders of the runtime directory.

- Here the goal is to implement this kind of "framework" packages dependencies when there are not part of the ambient framework. So, we have to store specific compilation and runtime assets in more structured probing folders (with `refs` and `runtimes` subfolders) ...

@GVX111 uses such a scenario in its dev and prod environments, he might test this.

Best

### CODE REVIEW

**Comment by Jetski5822** [comment]
@GVX111 whatcha think?

**Comment by GVX111** [comment]
@Jetski5822 i'll test at night and will write test result.

**Comment by Jetski5822** [comment]
Sound

**Comment by GVX111** [comment]
Error:on running from IIS:
Application startup exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> Orchard.OrchardException: Error while loading extension 'Orchard.Logging.Console'. ---> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by jtkech** [comment]
@GVX111 

So, as i remember, when you are running from IIS your packages are not resolved. So we grab them from probing folders (module bin folder and / or `app_data/dependencies` folder).

So, if you have deleted your module bin folder, your missing dll need to be in the `dependencies` folder. Or if the `dependencies` folder is not already populated, the missing dll need to be in your module bin folder ...

Would need more info on the missing dll(s). Can you debug under IIS? Diagnostics message are logged but maybe we need some log4net configuration ... You talk about `Orchard.Logging.Console`, so i assume the missing dll is `Microsoft.Extensions.Logging.Console.dll`, but not sure.

So, when packages are not resolved, for example, `Microsoft.Extensions.Logging.Console.dll` can't be nowhere. All needed assemblies need to be in module bin folders and / or in `dependencies` folder. This is the case when you publish the web app. Can you check this.


Best

**Comment by jtkech** [comment]
@GVX111 

Note that in a published context many ambient `Microsoft.* dependencies` are in the runtime directory. So, when packages are not resolved they are grabed from there. Maybe something has changed here, will try it.

**Comment by jtkech** [comment]
@Jetski5822, @GVX111 

Indeed, i've changed something here, seems i've made a mistake, will fix it asap

Thanks for the feedback

**Comment by jtkech** [comment]
Indeed, seems to be related to a change in 2 places in this PR. I seen a problem with an equality comparer in a HashSet. I was badly assuming that the `LockFileItem` class overrides the `Equals()` and `GetHashCode()` methods, as done with `LibraryAsset` ...

My mistake, @GVX111 can you try the last update.

Best.

**Comment by GVX111** [comment]
@jtkech great perfect awesome. i tried all possibility and it's working perfect. @Jetski5822 you can marge it.

**Comment by Jetski5822** [comment]
Saweet!!! - Good work chaps.

**Comment by jtkech** [comment]
@Jetski5822 @GVX111 

Glad to know it works. At least until the next unexpected scenario ;)

Best.

**Pull request merged**
