### PR TITLE
Migrating to VS2017

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by sebastienros** [comment]
Current issue is that the AmbientAssemblyLoader fails to load any assembly, even though they are in the bin.

**Comment by sebastienros** [comment]
Don't try to use `build.cmd` it's useless with csproj, do `dotnet restore` and `dotnet build` or just use VS2017.

**Comment by jtkech** [comment]
Would like to help but the free trial of VS2017 i loaded a few weeks ago has expired.

This would mean that modules are not already runtime loaded (as our precompiled views dll we had to load ourselves from its location). Oh, not sure, but maybe because the compiler see that the main app never reference these modules, so for some optimizations there are not loaded.

To quickly check this (if the assembly is really in the main app bin) you can try the following which works only if the assembly is not already loaded (you need to reference `"System.Runtime.Loader": "4.3.0"`).

            var assembly = System.Runtime.Loader.AssemblyLoadContext.Default
                .LoadFromAssemblyPath(
                    System.IO.Path.Combine(
                        System.IO.Path.GetDirectoryName(Assembly.GetEntryAssembly().Location),
                        extensionInfo.Id + ".dll"));

Maybe you need other build options, i can't check this, at least try to add this (we need anyway).

    <PropertyGroup>
        ....
        <PreserveCompilationContext>true</PreserveCompilationContext>
        ....
    <PropertyGroup>

Best.

**Comment by sebastienros** [comment]
Tried this too but it still fails for me. But I see that some assemblies load just fine, I will look at the differences between the ones that work and the ones that don't.

**Comment by sebastienros** [comment]
It works for me now. I added PreserveCompilationContext. It might also be necessary on the other main projects. I have some discrepancies between command line and VS, as VS would report missing required references on some modules, but cleaning the folder and rebuilding would fix things on the command line. I assume it gets lost with references somehow, like a bug in VS.

**Comment by agriffard** [comment]
OK. I managed to use my custom theme.

Can we merge the latest version of the master branch? For example, it would add the admin ui to enable and select themes.

**Comment by sebastienros** [comment]
This PR is based on the latest from master as of today.

**Pull request merged**
