### PR TITLE
Use the chevron right in the admin.

### PR DESCRIPTION
**Pull request by jtkech**
Just to use the chevron right in the admin, and also rotate it on the right.

### CODE REVIEW

**Comment by agriffard** [comment]
You pushed it to jtkech/Orchard2, not OrchardCms/Orchard2

**Comment by jtkech** [comment]
Oh yes just not to create another branch for this simple one on the main repo.
But sorry, indeed less easy for you to try it.

**Comment by agriffard** [comment]
May be you could share some screenshots?

**Comment by agriffard** [comment]
You inverted the rotation but we'd prefer up/down arrows : see #468

**Comment by jtkech** [comment]
Oh yes, because i also use the `fa fa-angle-right` in the .cshtml
chevron-right

**Pull request merged**
