### PR TITLE
Search module

### PR DESCRIPTION
**Pull request by sebastienros**

### CODE REVIEW

**Comment by agriffard** [comment]
There are errors retrieving these packages in Lucene/project.json :
`    "Lucene.Net.Analysis.Common": "4.8.0-alpha",
    "Lucene.Net.QueryParser": "4.8.0-alpha"`

That is why CI checks are failing :
`fail: Errors in /Users/travis/build/OrchardCMS/Orchard2/src/Orchard.Cms.Web/Modules/Lucene/project.json
fail:     Package icu.net 54.0.82 is not compatible with netstandard1.6 (.NETStandard,Version=v1.6). Package icu.net 54.0.82 supports: net40 (.NETFramework,Version=v4.0)
fail:     One or more packages are incompatible with .NETStandard,Version=v1.6.`

**Comment by sebastienros** [comment]
Yes, it's not looking in the orchard2 gallery on myget. Not sure why yet,
it's in the nuget config file though.

**Comment by sebastienros** [comment]
Fixed Travis

**Comment by Jetski5822** [comment]
Merged.

**Pull request merged**
