### PR TITLE
Fixes DisplayManagement unit tests.

### PR DESCRIPTION
**Pull request by jtkech**
@sebastienros 

- All `DisplayManagement` unit tests pass but see below.

- Some tests use the real `ShapeTableManager` which uses `GetEnabledFeaturesAsync()`. So i've done a `TestFeatureManager` (as done for `TestExtensionManager`) to implement this method. Then, without having a `ShellDescriptorManager`, it simply returns `TestExtensionManager.AvailableFeatures()`.

- Some tests use a `TestShapeTableManager` but which provides a `ShapeTable` of real type. Then, these tests add descriptors and bindings directly in the shape table. But here descriptors and bindings now are indexers. I could fix it by using a derived `TestShapeTable` (only when `TestShapeTableManager` is used).

- So, all seems ok but i've one question. In a real scenario, is it allowed to add descriptors and related bindings directly to a shape table, this after its creation and outside the `ShapeTableManager`?

Best.

### CODE REVIEW

**Comment by jtkech** [comment]
Forgot some unit tests in the `Descriptors` subfolder, will check it.

**Comment by jtkech** [comment]
- So, all tests pass.

- We prevent duplicate jobs in a single thread, but concurrent requests may build same descriptors.

- So, before seing if we need some locks, in the last commit i only minimize these possible useless jobs.

- This change was breaking 2 unit tests because the same provider for the same feature and shape type was used with a different alteration implementation. But we now have a static dictionary at the app level and we now first check if an entry already exists. So the descriptor was not created and saved.

- So, in these 2 tests, it's like modifying a module (not just enable / disable) without restarting the application. So, i fixed it by using a different descriptor name (= shape type).

Best.

**Comment by sebastienros** [comment]
If you have a cache, what you can do it return a Task from the concurrent dictionary and `await` it. So two thread will create a task, but only one of them will be executed.

**Comment by jtkech** [comment]
Ok, will try this.

**Comment by jtkech** [comment]
There are 2 main jobs:

1. Building alterations by using building strategies (shape providers)
2. Use them to alter descriptors before being saved in the dictionary.

- Indeed, the solution works for 2.

- As i remember, i also learned from you and already used in such a case a lazy factory. Right?

- But for 1, we know related dictionary keys only when alterations are built. So here it seems that the only thing we can do is to prevent 2 threads to create the same tenant/ theme shape table.

- I'll try to find a solution but it's only when threads execute simultaneously because we already use an excludedFeatures list, and knowing that there will be no duplicate jobs related to point 2.

Best.

**Comment by sebastienros** [comment]
Feel free to just open an issue to track that, you don't need to take of it now, even more if the solution is not obvious and without complexity. We might also just be able to live with it.

**Comment by jtkech** [comment]
Yes, you're right because a different object is always use when building a descriptor and it is saved at one point in the dictionary. I was just thinking to prevent multiple threads to e.g parse all `*.cshtml` ...

I'll think in parallel about a solution but without adding too much memory consumption.

So maybe you can merge this PR in the shapetable branch, then you can try it as it is.

>  return a Task from the concurrent dictionary and await it

Here did you also mean that it is worth to make `GetShapeTable()` an `async` method?

Best.

**Comment by sebastienros** [comment]
GetShapeTable should probably be async, and maybe the whole method chain up, but this can be done later.

**Comment by jtkech** [comment]
Ok, so i'll first wait your tests results, hope it works and improves memory consumption.

**Pull request merged**
