### PR TITLE
Populating the summary admin metadata

### LINKED ISSUE #384: Display Content item's owner and dates
ContentItem has PublishedUtc and ModifiedBy properties by no views that render them.
How can I specify on a content type that I want to display on front the published date or the author?

I ask this because there is no more CommonPart.

Same question for the edition:
There are no settings to specify I want to be able to edit the Created date or the owner.

And for the list of content items in admin:
How to display the last modified date and user?

### PR DESCRIPTION
**Pull request by sebastienros**
Alos creating DateTime and TimeSpan shapes

Fixes #384

### CODE REVIEW

**Comment by agriffard** [comment]
The 'delete' action is missing.

**Comment by agriffard** [comment]
Can we try to display the dates and the states on one line?

**Comment by sebastienros** [comment]
Trying to refactor what is there to make it modular and extensible first. Right now it's in a single monolitic shape and some other are not even used.

**Comment by Jetski5822** [comment]
@sebastienros ^^^ can you resolve?

**Comment by agriffard** [comment]
Do we display '- _Content type_', next to the title, in content items list?

**Pull request merged**
