### PR TITLE
Specific background task group periods.

### PR DESCRIPTION
**Pull request by jtkech**
Quickly done, need to be reviewed. Just to present the idea to have specific background task periods.

Best.

### CODE REVIEW

**Comment by sebastienros** [comment]
No thanks ;) I want the periods to come by configuration, not with a specific service.

**Comment by sebastienros** [comment]
And configuration will be done by code, which will also allow from settings.

**Comment by jtkech** [comment]
Ok, perfect

**Comment by sebastienros** [comment]
Feel free to challenge it, it's not the end of the discussion. We can skype if you want, I can't have had the best idea on the first try, without talking to anyone. I am even thinking about having all tasks run independently, without blocking one another.

**Comment by jtkech** [comment]
Oh yes, so not yet implemented but need to be done by configuration ... I'll think about it.

**Comment by jtkech** [comment]
Sorry, just came back on this. So, here some 1st thinkings.

- Do you mean by using the new aspnet core configuration model and maybe the new options pattern? It seems that ShellSettingsManager already use something here but didn't see yet this in depth.

- Do you mean by using the already implemented Settings files or other specific configuration files?

- `configuration will be done by code`, do you mean when no options found in a configuration file?

- I like the idea to have all tasks running independently, but maybe this involves too many resources.

- On another side, maybe good to have separate groups which executes several tasks with the same period. Moreover, here maybe good to have a priority property to control the tasks execution ordering.

Best

**Comment by sebastienros** [comment]
Quick answer, yes, groups are defining the period, any task in a group is executed synchronously in this group. Two groups means two parallel execution flows. If a task in a group doesn't finish in the period granted for the group, then the timer is not re-entrant.

I will take more time to explain what I mean for the configuration.

**Pull request closed without merging**
