### PR TITLE
Bring back the Orchard.OpenId module and migrate to OpenIddict beta2

### PR DESCRIPTION
**Pull request by PinpointTownes**
Note: due to the massive changes in the master branch, rebasing the `oauth2` was way too painful, so I decided to start from scratch, by copying the OpenID module created by @jersiovic on top of the `master` branch. This PR includes many bug fixes and uses OpenIddict beta2/ASOS RC1.

### CODE REVIEW

**Comment by jersiovic** [comment]
Upps, I was this morning spending time on uptating oauth branch to OpenIddict beta2.
Why don't you added your changes directly to oauth branch? I that way I can review easily what you changed. 
I was waiting migration to VS2017 was completed on master to do a rebase of oauth branch with master.

**Comment by jersiovic** [comment]
By the way my authorship won't be removed from the history of changes

**Comment by PinpointTownes** [comment]
> Upps, I was this morning spending time on uptating oauth branch to OpenIddict beta2.

I'm considering using OrchardCore for a client and I need token authentication for this project, so I couldn't wait. Since there was no activity, I went ahead and updated the OpenID module to use .csproj and OpenIddict beta2 (BTW, I reassigned the https://github.com/OrchardCMS/Orchard2/issues/276 ticket, which tracks this workitem)

> Why didn't you add your changes directly to oauth branch? In that way I can review easily what you changed.

The `oauth2` branch is in a terrible state: you rewrote almost all the history by force pushing in February:

image

Starting from scratch was much easier than trying to rebase the `oauth2` branch.

> By the way my authorship won't be removed from the history of changes

That's not really a problem, I can rewrite the commit added by this PR so it only mentions your name (I personally don't care much about that)

**Comment by PinpointTownes** [comment]
Note: if you prefer rebasing the `oauth2`, I'm fine: feel free to close this PR once you're done :call_me_hand:

**Comment by jersiovic** [comment]
It looks a good option, it will helps me to ease the rebase of branches in my fork on oauth branch that are also running in my clients. I have done the rebase locally, now I'm downloading VS2017 to see results.
After rebase I would had to convert Orchard.OpenId project.json to new format in VS20017 but if you have done it, it doesn't have sense I do the same, so it won't be included in the solution. 
So, I will check it looks good with VS2017 and I will push changes despite it won't include Orchard.OpenId in the solution. After your changes it will be ok.

**Comment by sebastienros** [comment]
Note: modules need to be referenced by the web project now that we have removed dynamic compilation/loading. 

> I'm considering using OrchardCore for a client and I need token authentication for this project, so I couldn't wait.

🎉

**Comment by jersiovic** [comment]
Done, I've rebased oauth branch on top of master, @PinpointTownes can you commit your changes on oauth branch?
Related to UI problems you can find keep in mind when this PR https://github.com/OrchardCMS/Orchard2/pull/563 is merged some problems will be fixed

**Comment by PinpointTownes** [comment]
> @PinpointTownes can you commit your changes on oauth branch?

This is a big task as there are many conflicts and unfortunately I don't have much time to do that ATM, so I'll merge this PR into the separate `openid` branch: if you find some time to take care of it, feel free to include the changes into the `oauth2` branch.

image

**Comment by jersiovic** [comment]
Well I don't think it should be hard. I will create a new branch from Oauth branch and there I will replace current openid code from yours . Then I would create a PR from that new branch to oauth branch in order to review your changes and comment them with you.

**Comment by jersiovic** [comment]
Done, I have created a PR with your code.
By the way I've noticed in your PR you skipped changes in oauth branch for Orchard.Users/Startup.cs file, related with cookie and dataProtectionProvider. 
https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.Users/Startup.cs#L92
I comment it to you just in case it can be relevant for your use case of Orchard 2 in a client.

**Pull request merged**
