### PR TITLE
Templates Persistence + little refactoring.

### PR DESCRIPTION
**Pull request by jtkech**
- Fixes Templates persistence

- Little refactoring on how we resolve a tag helper descriptor. The main change is that we first compute arguments names by replacing `_` with `-`, this in place of doing it for each required attributes.

It works but quickly done, so need to be reviewed.

**Update**: The little refactoring was not useful, so i reverted it. Then i just did a little tweak to use a string replace only once in place of 2 times.

### CODE REVIEW

**Comment by sebastienros** [comment]
My concern is that the bug you are fixing was fixed in yessql a few weeks ago, and also the one I am seeing on the blog recipe. I wonder if the version we are referencing would have a regression. I will check that. In the meantime could you just see on the `theagency` branch if the same bug exist? This branch didn't get the new yessql version. If there is no bug then it's probably a yessql regression.

**Comment by jtkech** [comment]
Ok, i will check it.

I need to leave, i will check it this night.

**Comment by sebastienros** [comment]
@jtkech I tried to edit the template and it works just fine, I can save the changes.

**Comment by sebastienros** [comment]
Found the issue, fixed it in dev and updated this PR

**Comment by jtkech** [comment]
Okay cool.

Just re-tried, indeed now it works.

**Pull request merged**
