### PR TITLE
Adding nanoScroller to admin left side bar.

### PR DESCRIPTION
**Pull request by matiasmolleja**
Add nanoScroller to left side bar

### CODE REVIEW

**Comment by agriffard** [comment]
I do not see the branch of this PR in the code history or in matiasmolleja/orchard2 fork. 

May be I am missing something but I can not test it and review it.

**Comment by matiasmolleja** [comment]
Hi,
I did the changes in the master branch, in matiasmolleja/orchard2.

**Comment by matiasmolleja** [comment]
Should I create a branch in my fork and create a new pull request?

**Comment by agriffard** [comment]
It's ok, I cloned matiasmolleja/Orchard2.

**Comment by agriffard** [comment]
But I don't get the difference that it brings.

Can you post 2 pictures with and without nanoscroller?

**Comment by matiasmolleja** [comment]
It's only visible when the left side bar is taller than window.
A few days ago Sebastien said on Gitter that it would be good to have this in the admin, so I wrote the PR.

**Comment by agriffard** [comment]
OK, the nanoscroller works.

Thank you for your contribution.

**Comment by Jetski5822** [comment]
Saweet :)

**Comment by Jetski5822** [comment]
Good testing @agriffard !!!! great work @matiasmolleja !!!

**Comment by matiasmolleja** [comment]
Thanks!

**Comment by sebastienros** [comment]
I need the same thing in the Media folders, I hope I can understand how to repro it.
Also if nobody has already, I will try on mobile when the menu is triggered by the burger icon.

**Pull request merged**
