### PR TITLE
Dotnet sdk/2659

### PR DESCRIPTION
**Pull request by Skrypt**
Changes to project.json schema.
https://github.com/aspnet/Announcements/issues/175

### CODE REVIEW

**Comment by sebastienros** [comment]
Looks good

**Comment by alexbocharov** [comment]
No changes for `...\Orchard2\test\Orchard.Tests\project.json`.
@Skrypt Please add the changes for the test project

**Comment by Skrypt** [comment]
done

**Comment by alexbocharov** [comment]
Cool! :thumbsup:

**Comment by Jetski5822** [comment]
Merged after three thumbs up!

**Pull request merged**
