### PR TITLE
Allowing behavior: hide on checkbox checked

### PR DESCRIPTION
**Pull request by jersiovic**
Solves this issue #518
Now a checkbox can be set to hide sth when it is checked setting its attribute data-toggle="collapse active"
So, in the sample mentioned in the issue, the desired behaviour is accomplished in this way:
```
<input asp-for="TestingModeEnabled" type="checkbox" data-toggle="collapse active" data-target="#certArea" class="form-check-input" checked="@Model.TestingModeEnabled"/>
```
Oposite to a previous PR I've rebased this branch on master to get last bootstrap bits replacing 'in' class per 'active' class.

This PR also forces the update of 'collapse' and 'show' classes on the load of the page to avoid current Bootstrap problem when a checkbox is loaded: Despite their initial value should cause target is shown or hidden it doesn't work.

### CODE REVIEW

**Comment by jtkech** [comment]
I tried it by using `data-toggle="collapse active"` in the Lucene `ContentIndexSettings.Edit.cshtml` and it works great. Just one thing when 1st displayed it doesn't expand even it is unchecked. But maybe intended to be done in another script, or maybe because of some bootstrap changes.

So, for infos in my tests i needed to replace the following.

        // Expand the section if necessary
        var target = $($(this).data('target'));
        if (!$(this).prop('checked')) {
            target.addClass('collapsed');
        }

With

        // Expand the section if necessary
        var target = $($(this).data('target'));
        if (!$(this).prop('checked')) {
            target.collapse('show');
            // target.addClass('show'); // this also works
        }


I also needed to do the same in the previous function if i re-use `data-toggle="collapse"`.

Note:  Do we also need in the PR the gulp output (`TheAdmin.js`)?

Best.

**Comment by jersiovic** [comment]
I have rebased the branch on master and added files produced by gulp like TheAdmin.js, ...

In my case I use it here https://github.com/OrchardCMS/Orchard2/blob/oauth2/src/Orchard.Cms.Web/Modules/Orchard.OpenId/Views/OpenIdSettings.Edit.cshtml for input with ID = #TestingModeEnabled
This is the method is executed on every load to sync the state on load:
`
function refreshTestingModeEnabled() {
        var testingModeEnabled = $("#TestingModeEnabled");
        $("#certArea").collapse(testingModeEnabled.prop("checked") ? "hide" : "show");
    }
`

**Comment by jtkech** [comment]
Oh yes i see, you don't see it because you use a refresh function. But maybe good to do the above change, and also in the previous function because i think there was already a little issue.

E.g when i edit the body part of the page content type, even the `Include this element index` option is already checked, the section is not expanded on first load.

Note: To check te above in the last master, in `ContentIndexSettings.Edit.cshtml` you need to change `@model Lucene.Settings...` with `@model Orchard.Lucene.Settings...`.

So, can you check if with the above change (in both functions) you can also get rid of some part of your refresh function (unless you need to execute it in other circumstances).

Then, i can't merge this PR myself but i will approve it because i already needed such a behavior where it's not obvious to find another option with the opposite meaning.

Best.

**Comment by sebastienros** [comment]
Please merge master into this branch, then regenerate the static assets (gulp rebuild) and commit them.
Once done I will merge.

**Comment by jersiovic** [comment]
@sebastienros I've rebased just now the branch on master. However gulp rebuild doesn't changed .js and .css files cause there aren't any change since 4 days ago when I did a gulp rebuild and committed changes on this branch. So, you can merge this PR

**Pull request merged**
