### PR TITLE
#121: Missing assembly in Orchard.DisplayManagement

### LINKED ISSUE #121: TagHelpers don't work anymore
@jtkech I think you are the last one who touched this roslyn compilation after I had fixed it. If you try to add `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"` to a view and use one of the tag helpers (like form) then it will complain about a reference missing. It means it's not adding the references that are in project.json.

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #121 

Add `Microsoft.AspNet.Mvc.TagHelpers` assembly in `Orchard.DisplayManagement` project.

### CODE REVIEW

**Comment by sebastienros** [comment]
I think it's a wrong fix as there is no direct dependency from `Orchard.Displaymanagement` but because you are adding it and this project is loaded, the view will find the assembly.
The Mvc.TagHelpers assembly is just adding specific tag helpers, the DisplayManagement module uses the extensibility points, not the actual tag helpers.

I might take this as a temporary solution but I will keep the issue open so we can find the correct solution, otherwise we'll hit the same issue with any other reference. For instance let's imagine your module depends on another package, boom, same issue.

**Comment by jtkech** [comment]
@sebastienros oh i see, you're right, interesting. Can't right now, i'll take a look this night.

**Comment by sebastienros** [comment]
Maybe we should wait until rc2 is released as it will completely change how compilation is done.

**Comment by jtkech** [comment]
@sebastienros 

Ok, no worries, but i just got something that seems to work. Not sure it's a good fix that works in all scenarios, but it's a last attempt, see this PR #128...

Best

**Pull request closed without merging**
