### PR TITLE
Manage themes from admin

### PR DESCRIPTION
**Pull request by agriffard**
Recreate #507 PR because there were too much conflicts to resolve.

### CODE REVIEW

**Comment by agriffard** [comment]
It seems there is still an error (not always occuring) when you enable a theme, similar to the one previously described about the cache manager.

**Comment by sebastienros** [comment]
What's the status of the branch?

> It seems there is still an error (not always occuring) when you enable a theme

**Comment by agriffard** [comment]
The error still occurs.

**Comment by agriffard** [comment]
I tested again after the merge and the error doesn't occur anymore.

**Comment by Jetski5822** [comment]
@sfmskywalker hey Sipke, are you happy with this PR? if so, could you approve it?

**Pull request merged**
