### PR TITLE
Update Travis CI settings

### PR DESCRIPTION
**Pull request by alexbocharov**
@sebastienros @Jetski5822 
Fixed build in Travis CI

### CODE REVIEW

**Comment by sebastienros** [comment]
Still failing?

Should we have our own scripts btw, because we are currently using the ones from the aspnet projects, but we don't need all the complexity.
For instance on appveyor I changed it to just be `dotnet restore` and `dotnet build`, knowing the I load a `Visual Studio 2017 RC` image first that contains dotnet core runtime and SDK.

I assume a simple script for travis would be to load the runtime/sdk manually, and do the same.
And run the tests also, this is something I forgot on appveyor.

**Comment by alexbocharov** [comment]
At the moment don't pass tests. I should simplify logic of build? Maybe we need to configure a build through MSBuild?

**Comment by sebastienros** [comment]
Yes, we need to use msbuild, and also remove mono dependency.

**Comment by alexbocharov** [comment]
Ok, I'll do it

**Comment by sebastienros** [comment]
Looks good so far, I can see some green on travis right now

**Comment by alexbocharov** [comment]
> Looks good so far, I can see some green on travis right now

I need to look at some moments of build

**Pull request merged**
