### PR TITLE
Updating dependencies to rc2-final 

### PR DESCRIPTION
**Pull request by alexbocharov**
Fixing dependencies

### CODE REVIEW

**Comment by alexbocharov** [comment]
@sebastienros We will follow `rc2-final` or `aspnetcidev` feed?

**Comment by sebastienros** [comment]
I am torn. final is safe for progression, but dev would let us catch any change or regression. Let's stay on final right now, and test on dev some time before RTM.

**Comment by alexbocharov** [comment]
Ok, I will make at myself a branch and I will support it for dev branch. It will allow us to avoid problems with updating

**Comment by alexbocharov** [comment]
Not actually

**Pull request closed without merging**
