### PR TITLE
Wildcard Extensions and Shell based extensions

### PR DESCRIPTION
**Pull request by Jetski5822**
- Changing Search paths to be wildcard based. i.e. "Modules/ **" or "Themes/ **"

- Added a shell extension info and provider. This allows you to do this, "AppData/ Sites/ **/ Modules/ **". This will build up a new ShellExtensionInfo with a few additional details on it.

- The Ids for Shell Extensions are <ShellName>_<ExtensionId> : This should avoid any conflicts.

Fixes: https://github.com/OrchardCMS/Orchard2/issues/324

### CODE REVIEW

**Comment by Jetski5822** [comment]
@bleroy What do you think? Would this satisfy your requirement?

**Comment by Jetski5822** [comment]
@jtketh what do you think of this PR?

**Comment by jtkech** [comment]
>what do you think of this PR?

- Wow, seems awesome.

But so many things, maybe i need 2 or 3 days more to fully understand. Can't right now, need to leave but tomorrow night i'll began to see it more in depth.

At least i think i already got the main idea to separate what we load and from where, and what we can enable based on the tenant / shell. Not sure about the defaut location under `App_data`, but just a feeling. Maybe just `{tenant}/Modules` and  `{tenant}/Themes`.

As a side note, with minor changes (don't remember but can retrieve them) i was also able to use a lightweight theme extension which has no source and no project files and then no assembly, only a manifest. So maybe good that a tenant could have full modules / themes and / or only lightweight themes.

Best.

**Comment by jtkech** [comment]
Sorry, i didn't have much time and i was fixing an issue with the precompiled views tool, i will try it asap ;)

**Comment by jtkech** [comment]
I began some tests here with shell themes for simplicity. In these 1st tests most of the things works and here i mainly talk about little drawbacks i've seen.

- Setup and unit tests ok.

- Then i created 2 tenants so i have `Default`, `Alpha` and `Beta` tenants.

- Then i've done 3 copies of `TheTheme` renamed `TheTheme1`, `TheTheme2` and `TheTheme3`, one per tenant under `App_Data/Sites/{tenant}/Themes`. I also deleted binaries folders, project files unless `project.json`, i also renamed the namespace in `PlaceHolder.cs`, and done a `dotnet restore`.

- Then, i don't know why but my `app_data` folder was not with upper cases as `App_Data` and the 3 new themes was not compiled and loaded. When i renamed it to `App_Data` it seemed to work. **So, it seems that the search paths are case sensitive, is it intended?**

- Note: Didn't check the code but when you construct a path you can use `Path.DirectorySeparatorChar` but when you check a path notice that the separator could be also `Path.AltDirectorySeparatorChar`.

- Then i've modified the `Orchard.Modules` not to filter themes and display all extensions. **Then all themes was displayed but not filtered per tenant** but i think i understood why. In `AdminController` you have.

        private bool ExtensionIsAllowed(IExtensionInfo extensionDescriptor)
        {
            if (extensionDescriptor is ShellExtensionInfo)
            {
                ...
            }

    But unfortunately `ThemeExtensionInfo` can't be cast to `ShellExtensionInfo`. Under the debugger i can see that its private variable `_extensionInfo` is of type `ShellExtensionInfo`, but not the theme extension itself. I think it would work with shell modules (will try it), but we also need to filter shell themes.

- Then, in the `Beta` tenant i've enabled `TheTheme3` and selected it. First it was not working but under the debugger i've seen that the themeId was `Beta_TheTheme3`. So i selected it by this name and then i could see in the front end that the layout of the correct theme was used, so ok.

- But i remembered that the regular extension provider init the extension id to its subfolder name and in different places paths are resolved by assuming this. E.g when a project is compiled the assembly name is the name of its folder, and right now we are assuming that an extension id = its assembly name.

- Indeed, under the debugger i could see that **right now returned assemblies of themes extension entries are null**. It was working because only razor views was used.  **So, in some places we would need to re-use the extension subpath (to retrieve its folder name) in place of using its id**.

- But anyway, **we need different assembly names** to be loaded and stored in the shared dependencies folder. So, because this is the project model which assigns to a project (and then its assembly) the same name of its folder, **we need different extension folder names** (last subfolder). So it seems that the regular extension id would need to be already differentiated.

- Otherwise we would need e.g to force the assembly name to be equal to the differenciated extension id (not the opposite), the compiler (dyn or not) would need to use another option to change the outputed assembly name ... But maybe too complex when modules becomes dependents on each other.

- Finally, with minor changes **it already works as it is but with lightweight themes** (without any assembly). Implementing e.g a theme without any assembly (and without c# and project files) doesn't need many changes. Currently we don't see anything because the logger is not enabled.

Best.

**Comment by Jetski5822** [comment]
I'll reply more later, but yes, paths are case sensitive. This is due to support for other environments.

**Comment by jtkech** [comment]
>Paths are case sensitive. This is due to support for other environments.

Ok, so as i understand when we check for a path we have the choice to be case sensitive or not, and the important thing is to respect the case e.g when we create a folder .

So at least, in `AddWebHost()` we would need to change this.

    internalServices.AddExtensionManagerHost("app_data", "dependencies"); // change this line
    internalServices.AddExtensionManagerHost("App_Data", "dependencies"); // to this line

And maybe (not sure) we could be more relax when we grab extensions.

    Matcher matcher = new Matcher(StringComparison.Ordinal); // change this line
    Matcher matcher = new Matcher(); // to this line


Best.

**Comment by Jetski5822** [comment]
Closing for now.

**Pull request closed without merging**
