### PR TITLE
Experimental dynamic compilation

### PR DESCRIPTION
**Pull request by jtkech**
@sebastienros 

So, we already can dynamically load a module and compile its razor views. Here we try to dynamically compile a module, it's very experimental and only to show my code. I'll update it during the week end as it will progress.

- The idea is to directly use an adapted & lightweight compiler without relying on the dotnet cli sdk.

- Currently you need to copy manually `csc.dll` and `csc.runtimeconfig.json` from the dotnet sdk you use to the orchard.web bin folder. No nuget reference for these files but I'll embed them in the orchard.web app and specify to copy them on compilation ...

- See in `ExtensionLibraryService.cs` how i use a managed compiler, here for testing i only check if the module dll is in its bin folder. If not i compile it and then i runtime load it. Note: not to mix problems, i've inhibited the `AmbientExtensionLoader`.

- Right now, the only test i've done is to remove the `bin/debug/netstandard1.5` folder of the `Orchard.Demo` module, then run the app. And it works, the module was dynamically compiled and loaded.

- I started with about 30 files grabbed from the dotnet cli repo but i already have simplify the implementation because it's not a root project, we don't need to compile dependencies, no specific runtimes folders to be generated for a portable library ...

- I also have removed some implementations related to resource manager (e.g `.resx` files), scripts runner e.g for pre and post compilation scripts ...

- So, now i only use about 10 files but most of them are related to the command line options, arguments, types, parsing. So in our usage i think i can get rid of many of them. Maybe also, i can remove some implementation related to diagnostics, error parsing / reporting ...

Best

### CODE REVIEW

**Comment by sebastienros** [comment]
Ok, so you are actually embedding the dotnet build source code which removes the dependency on the sdk. Looks good to me. Would be nice if that was a supported solution like a separate nuget package, or at least a separate project in Orchard so we can rev it independently.

We need to also think about how we can deploy Orchard and the modules. There are build in command (dotnet pack) to deploy, and events to add more file (like the modules?) as this will impact how the binaries are deployed ... but good progress, I like it.

**Comment by jtkech** [comment]
You are totally right. In fact i only embed dotnet compile (not build), it will be our responsability to compile or not an extension. For the rest i see what you mean, but right now not so clear for me.

Currently i try to make it simpler step by step. E.g, i think we don't need all the stuff related to error diagnostics, errors reporting ... When we dynamically compile i think we only need to know if it succeeds or not and log some simple orchard infos. Same remark on some stuff related to command arguments checking.

Do you agree on this?

For infos: The fix we have proposed in the aspnet forum about view compilation seems to solve the issue for someone. I've seen some recent updates on roslyn compilation but they didn't use our fix. On view compilation they use more metadata references grabbed from the application parts manager. But they use the Dependency context. Not sure but i think this means that we would need to compile modules with the preserveCompilationContext option. This to have all dependencies infos embedded in the dll itself (without using project.json), but module dlls will be much more bigger. So not sure it's a good solution for us, will see.


Best.

**Comment by jtkech** [comment]
@sebastienros 

I've removed all the interface between the built in dotnet-compile and the csc compilation. Before, all compilation arguments was translated / parsed in 2 command line syntaxes, through responses files ...

Now, i only use one file `CSharpExtensionCompiler.cs`.

**Comment by GVX111** [comment]
can't compile Orchard.Logging.Console CSharpExtensionCompiler.Compile()  returning false. 
ExitCode = 1;

**Comment by jtkech** [comment]
@GVX111 thanks for trying it.

Do you use my last updates and applied on the sebros/cdshapes branch? Just re-tried, it works on my side, maybe i don't use the same dotnet version, i don't use yet vstudio tools ...

Is the issue only for `Orchard.Logging.Console`? For testing, you can compile all modules through vs tools and then delete the bin folder of only one module, this for testing each one step by step.

You know, you need to copy manually `csc.dll` and `csc.runtimeconfig.json` from the dotnet sdk you use to the orchard.web bin folder. No nuget reference for these files.

I've tried to embed them in a orchard.web/Tools folder and used `copyToOutput` in project.json `buildOptions` for this folder. then it works for me by using in the code:

    Command.Create("Tools/csc.dll", cscArgs)

For me the only concern i have is with the needed `csc.runtimeconfig.json` where there is a specific version: (here you can see the version i use)

    {
      "runtimeOptions": {
        "framework": {
          "name": "Microsoft.NETCore.App",
          "version": "1.0.0-rc2-3002702"
        }
      }
    }

Here i would like to use e.g `"version": "1.0.0-*"`.

Best.

**Comment by GVX111** [comment]
i downloaded your branch compiler and i'm use dotnet version:  3002702
when i'm building manually Orchard.Loggin.Console it working and creating bin folder with dependecies.  
Can you use csc.dll from dotnetsdk environment? why we need to copy csc in Orchard.Web/bin?

**Comment by jtkech** [comment]
It's to work without the dotnet sdk, e.g in a prod env where only dotnet core is installed, not the sdk.

But maybe useless if we want to use dyn compile only on a dev env, as everyone i discover things one by one, will see ...

**Pull request merged**
