### PR TITLE
Fixes #330 - use PageTitleSeparator

### LINKED ISSUE #330: PageTitleBuilder: use site setting PageTitleSeparator
By default, the PageTitleBuilder implementation should use siteSettings.PageTitleSeparator, not " - ".

See Orchard.DisplayManagement\Title\PageTitleBuilder.cs line 47 :
`_titleSeparator = new HtmlString(" - ");`

### PR DESCRIPTION
**Pull request by Jetski5822**
Use PageTitleSeparator rather than " - ".

### CODE REVIEW

**Comment by sebastienros** [comment]
We should not have a .Result in a code path that is used so much, like several times on every request.
Let's make all the code path async.

Also, maybe we should not have this option, looks like overkill. Maybe a shape, a template, or a view component would be easier to change the whole title generation (for theming purpose). But that's a different topic.

**Comment by Jetski5822** [comment]
Yeah I wasent sure about this hence a PR, I wasent sure if I should change the whole pipeline on this.

**Comment by sebastienros** [comment]
Should we have this logic in a shape template instead of as a service+db ? After all who cares about changing it, and if so, then one could override a template in the theme. If you agree I can do it, just close the PR.

**Comment by sebastienros** [comment]
Replaced by https://github.com/OrchardCMS/Orchard2/pull/410

**Pull request closed without merging**
