### PR TITLE
ShapeTable rebased on master.

### PR DESCRIPTION
**Pull request by jtkech**
So i've done a new PR to be cleaner.

@Jetski5822 about features ordering i could do it, e.g with what i am doing temporarily here in `DefaultShapeTableManager.DescriptorHasDependency()` but rather e.g in the new `FeatureExtensions.DependencyOn()` or in `FeatureInfoList.HasDependency()`.

But i would like to use the new `ManifestExtensions (e.g IsTheme())` but they are defined in `Orchard.DisplayManagement`. So, need to think about how to organize things.

### CODE REVIEW

**Comment by jtkech** [comment]
@sebastienros all the shapetable work rebased on master, conflicts solved and all tests pass.

Needed to adapt feature ordering (see below). here i propose a solution to be reviewed by @Jetski5822.

@Jetski5822 

So here i implement feature ordering by explicit and also implicit dependencies. Please review, it's just a suggestion. Implicit dependency meaning a theme which "depends" on all modules and its base theme.

See `HasDependency()` in `FeatureInfoList.cs` and `FeatureExtensions.cs`, and how it is used in `DefaultShapeTableManager.DescriptorHasDependency()`.

    item.Value.Feature.HasDependency(subject.Value.Feature)

Not to change projects references i also moved 2 files e.g `ManifestExtensions.cs` from `Orchard.DisplayManagement` to `Orchard.Environment.Extensions.Abstractions`

**Comment by Jetski5822** [comment]
So what I was trying to achieve is to make the abstractions and implementation of extensions not know anything about Themes, or Core, or Themes, or X/Y/Z etc...  Extensions should be just that, extensions no discrimination or ordering by type, only priority and dependency.

Themes are just extensions, enabled Extensions. So why doesnt a theme just have a dependency on a Derived theme, and if that theme has a dependency on a feature, have that theme have a dependency on that? Want me to pull your branch and take a look?

**Comment by jtkech** [comment]
@Jetski5822 

I was just decribing what we need because of the current architecture and, indeed, it can be done differently. I agree, in place of defining a BaseTheme, a theme could just have a dependency on it (i proposed the same for this point in one of my previous comments). 

But e.g for shapes, themes need to always win, so they have an implicit dependency on all modules (core ones included). And i suspect that this specific ordering is also required e.g when calling some handlers / filters ... So here, the problem is that a theme would need to define a depency for all possible modules.

So here, not to interfere with your work, i will revert the change related to feature ordering, and, waiting for the above, right now i will re-implement it specifically at least for the shape table manager.

Best.

**Comment by sebastienros** [comment]
Should I wait for @Jetski5822 's fixes to get in master before merging this one?

**Comment by jtkech** [comment]
@sebastienros i think you can merge it.

I've just added a few lines of code to always have the themes at the end of the features list. When it will be done at the feature manager level, i will be able to remove these lines through a simple PR.

@Jetski5822 is right, a theme is just an extension, but it is a theme so it has an implicit dependency on all modules, and we can't define this specificity through a manifest file.

**Comment by sebastienros** [comment]
@Jetski5822 you could create a concept named "Convention" that would have the logic for themes, without affecting the extensions themselves. This conventions would be able to make any theme lower that a module, or make a theme lower than its base theme. So a convention can either compare two extensions, or say "No, don't care". They could be with priority. Like a DependencyConvention would look at dependencies. a ThemeConvention would look at the extension type.

**Comment by jtkech** [comment]
@sebastienros forgot to say that maybe good to try this one on master before having to resolve other conflicts. Just a few lines of code have been added related to theme implicit dependencies.

**Comment by sebastienros** [comment]
> At least one approved review is required by reviewers with write access

**Comment by jtkech** [comment]
Ok, no worries

**Comment by sebastienros** [comment]
Well, the question is who is blocking the merge with a review, not me

**Comment by sebastienros** [comment]
ah, wait, i get it now

**Pull request merged**
