### PR TITLE
I can edit in vs2015 and run it?

### PR DESCRIPTION
**Pull request by freemsly**
I can edit in vs2015 and run it?

### CODE REVIEW

**Comment by alexbocharov** [comment]
You will not be able to get a working version of the project at the moment. This code isn't ready. I'm going to remove support DNX.

**Comment by Jetski5822** [comment]
Some seriously awesome work man,  I'maway for another two weeks, @sebastienros can you take a look?

**Comment by Jetski5822** [comment]
Wow ok :)

**Comment by sebastienros** [comment]
Yeah, easier ;) I just did that for YesSql and then fixed what remained to be fixed

**Pull request merged**
