### PR TITLE
Harvest shapes in Views/Shared/Shapes.

### PR DESCRIPTION
**Pull request by jtkech**
Todo

- Need to check all views i'm able to request.

- Rebase on master to check if the precompiled tool still works.

Questions

- Maybe good to still have `Items, Parts, Fields, Elements` subfolders just to organize things e.g when a module has many razor views, i don't know.

Note: i've already seen that all views, which starts with an underscore as `_ViewImports.cshtml`, now are not parsed.

Best.

### CODE REVIEW

**Comment by sebastienros** [comment]
Is it possible that the harvesters actually look in any subfolder of Shapes? Without affecting how controller views are fetched.

**Comment by jtkech** [comment]
Indeed we first need to check this kind of things. I'll do more tests tomorrow.

**Comment by jtkech** [comment]
Related unit tests fixed by using the right subPath `Views/Shared/Shapes` (in place of `Views`).

**Comment by sebastienros** [comment]
I will explain this change during next meeting, then merge it if they agree. You don't need to fix the conflicts, I will when I merge. There are also new templates that need to be moved.

**Comment by jtkech** [comment]
Ok

**Comment by jtkech** [comment]
Seems to be obsolete, anyway it will be easy to re-do it.

**Pull request closed without merging**
