### PR TITLE
Shapetable branch after merging master and solving conflicts

### PR DESCRIPTION
**Pull request by jtkech**
@Jetski5822 as said in my last comment in #325 when ordering by dependencies, a theme "depends" on all modules (at least in O1, maybe we want something different in O2) and on its base theme (if it has one). As extension manager was implementing in its `HasDependency()` method.

Note: I think it also needs to "depends" on core modules where in O2 the manifest type is null. So, maybe there was already a missing check in the previous extension manager in O2.

So, here i've done some updates just to show what i mean. In `ManifestExtensions` i've added some null checks and the `IsCore()` extension. And see in `DefaultShapeTableManager.DescriptorHasDependency()` where i not only use `Feature.DependencyOn()` but also what extension manager was doing (and also used `IsCore()` because in O2).

By doing this, themes are at the end of the list and in the right order (at least for shapes management). Note: Also, in unit tests i didn't need anymore to add a base theme in the features list of a derived theme (as it seems not to be done elsewhere).

So, it's just to show what i mean, because it needs to be implemented at another level e.g in `FeatureInfoList` and / or in `FeatureExtensions`, this to always have the right features ordering everywhere.

maybe it needs to be discussed if e.g in O2 we want that a derived theme specify its base theme in its dependencies (not through the base theme marker), but a theme "depends" on all other modules, so ...

Best.

### CODE REVIEW

**Comment by Jetski5822** [comment]
Yo yo - I agree that we need both, I have done this on a separate branch, methods names on extensionmanager called "GetFeatureDependencies" and "GetDependentFeatures". Just fixing a bug then will push it up, I dont think it will conflict with your work.

**Comment by Jetski5822** [comment]
@jtkech  pushed my stuff to master. Is this PR ready to roll? @sebastienros reviewed it in another PR right?

**Comment by Jetski5822** [comment]
Opps conflict in one file :( 'DefaultShapeTableManagerTests.cs' - want me to fix it?

**Comment by jtkech** [comment]
@Jetski5822 yes in another PR which is already closed and merged but in the shapetable branch for testing before merging in master. But, because it is tied to your work, to anticipate conflicts, i've merged master on my local branch. But because the previous PR is already closed, i opened this one.

But no worries i will solve the conflict and / or create a new PR rebased on the last master directly.

**That's said, the main point in my previous comment was about how features are now ordered**. When using `OrderByDependenciesAndPriorities()` in `FeatureInfoList`, you pass a `HasDependency` function which do a `IFeatureInfo.DependencyOn()` which only relies on the `Dependencies` collection.

But it doesn't implement as before **the case of themes which need to be at the end of the list because they "depend" on all modules** (core ones included with a null manifest type), and before their base theme.

See in `DefaultShapeTableManager.DescriptorHasDependency()` how it is done temporarily.

Best.

**Comment by Jetski5822** [comment]
Interesting, let me have a think about this. I think I understand the issue.

**Comment by jtkech** [comment]
Ok, not urgent at all for me.

**Comment by jtkech** [comment]
Opened a new one rebased on last master.

**Pull request closed without merging**
