### PR TITLE
Prevent Setup if the password is invalid

### LINKED ISSUE #817: An invalid password doesn't prevent setup
Then the site is in a corrupted state as the admin user is not created.

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #817

### CODE REVIEW

**Comment by agriffard** [comment]
It doesn't prevent invalid password for me and the initial problem #817 is still existing, after the first bad attempt, the database is half created.

**Comment by sebastienros** [comment]
Did you refresh your scripts in the browser? It worked correctly for me.

**Comment by agriffard** [comment]
Yes, I refreshed the scripts.
Here are my tests. P=Password, C=Confirmation
P= orchard, C= orchard => is invalidated because Password must contain A-Z.
P= orchard, C = orchard => Setup is called and database is half created.

**Comment by sebastienros** [comment]
Thanks, I will try again.

**Comment by azGreg** [comment]
If I have a cached password, and do not tab through the password field (only use the validate password field) the form submit button does nothing. There is no indication as to why nothing is done.

Would it be better for the password field to start without being cached?

**Pull request merged**
