### PR TITLE
Updating dependencies to CLI version 1.0.0-rc2-002673 

### PR DESCRIPTION
**Pull request by alexbocharov**
@sebastienros @jtkech I updated depending to the latest version

Used [DOTNET CLI 1.0.0-rc2-002673 for Windows x64](https://dotnetcli.blob.core.windows.net/dotnet/beta/Installers/1.0.0-rc2-002673/dotnet-dev-win-x64.1.0.0-rc2-002673.exe)

### CODE REVIEW

**Comment by Skrypt** [comment]
We are already @ 2678 this morning. Why not using " -* " everywhere ? Is there a reason why we keep the versions ?

**Comment by sebastienros** [comment]
We can't use -* or it will request nuget all the time for new versions, and it will be very slow to compile, and will also break more often. We should pro-actively update the version, but push to the repos only when it works, or we'll all have to face issues with breaking changes.

**Comment by Skrypt** [comment]
Alright makes sense.

**Comment by alexbocharov** [comment]
@sebastienros We use version `2.0.0` for all packages?

**Comment by alexbocharov** [comment]
> We are already @ 2678 this morning
I was guided by the project [KoreBuild](https://github.com/aspnet/KoreBuild/tree/release/build) and [aspnetcirelease feed](http://myget.org/gallery/aspnetcirelease).

Also I aligned dependences.

**Comment by sebastienros** [comment]
No, for our packages we use -*, but for .NET Core we use specific ones

**Comment by alexbocharov** [comment]
No, I speak about it 

```json
{
  "webroot": "wwwroot",
  "version": "2.0.0-*",
  "dependencies": {
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-20750",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-20750",
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002426",
      "type": "platform"
    },
    "Orchard.Hosting.Console": "2.0.0",
    "Orchard.Hosting.Web": "2.0.0",
    "Orchard.Core": "2.0.0",
    "Orchard.Contents": "1.0.0",
    "Orchard.ContentTypes": "1.0.0",
    "Orchard.Demo": "1.0.0",
    "Orchard.DynamicCache": "1.0.0",
    "Orchard.Lists": "1.0.0",
    "Orchard.Logging.Console": "2.0.0",
    "Orchard.Resources": "1.0.0",
    "Orchard.Setup": "2.0.0",
    "Orchard.Themes": "1.0.0",
    "SafeMode": "1.0.0",
    "TheAdmin": "1.0.0",
    "TheTheme": "1.0.0"
  },
  "buildOptions": {
    "emitEntryPoint": true,
    "debugType": "portable",
    "preserveCompilationContext": true,
    "copyToOutput": [
        "Views",
        "web.config"
    ],
    "compile": {
      "exclude": [
        "wwwroot",
        "node_modules",
        "App_Data",
        "Core",
        "Modules",
        "Themes"
      ]
    }
  },
  "frameworks": {
    "netstandardapp1.5": {
      "dependencies": {
        "NETStandard.Library": "1.5.0-*"
      },
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "tools": {
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-rc2-20750",
      "imports": [
        "dnxcore50",
        "portable-net451+win8"
      ]
    }
  },
  "packExclude": [
    "node_modules",
    "bower_components",
    "**.kproj",
    "**.user",
    "**.vspscc"
  ],
  "packOptions": {
    "type": "git",
    "url": "https://github.com/OrchardCMS/Orchard2"
  },
  "scripts": {
    "prepublish": [ "gulp publish" ],
    "postrestore": [ "gulp publish" ]
  }
}

```

**Comment by jtkech** [comment]
@sebastienros @alexbocharov 

In my PR #158 because i've removed modules / themes dependencies in the orchard.web project. I use a fake project with such a file but with minimal options, without generating dll for this fake project ...

This to be able to compile all projects libraries (except orchard.web app) through a new vscode command.

Best.

**Comment by alexbocharov** [comment]
Resolve conflicts

**Pull request merged**
