### PR TITLE
Orchard.CodeGeneration module

### PR DESCRIPTION
**Pull request by timmahon**
Initial port of the Orchard.CodeGeneration module from Orchard 1.9.2 which generates Orchard 2.0.x compatible modules and themes.

Current supported commands are:-

```
codegen module <module-name> [/IncludeInSolution:true|false]
codegen theme <theme-name> [/IncludeInSolution:true|false][/BasedOn:<theme-name>]
```

### CODE REVIEW

**Comment by sebastienros** [comment]
Looks good to me. I even checked that you didn't include the `web.config` and took care of the `_ViewImports.cshtml`. That's great.

**Comment by sebastienros** [comment]
I am wondering how the orchard command line is started? Haven't tried it yet.

**Comment by timmahon** [comment]
navigate to the Orchard.Web directory and from a command prompt

```dnx run``` 

will get you a console rather than the web

**Comment by Jetski5822** [comment]
dnx run

-----Original Message-----

**Comment by Jetski5822** [comment]
So this looks cool, outta interest,did you look at this https://github.com/aspnet/Scaffolding ? I am wondering if we need to take a look at readapting this module to use scaffolding.

**Comment by timmahon** [comment]
No - I hadn't seen that - I'll take a look... Thanks

**Comment by sebastienros** [comment]
Please open an issue to talk about this feature and track the progress. We need to decide how this will be done.

**Pull request closed without merging**
