### PR TITLE
Allow for possible multiple view engines

### PR DESCRIPTION
**Pull request by petedavis**
Looking how RazorGenerator was built for full .Net stack, it would not be possible to use equivilant in Orchard as it injects a new view engine, where this code will never fall back to the original razor view engine.

Credit to: 
https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.ViewFeatures/ViewEngines/CompositeViewEngine.cs

### CODE REVIEW

**Comment by Jetski5822** [comment]
@agriffard all good from yourside?

**Comment by agriffard** [comment]
@sebastienros has approved. I haven't tested and do not really understand what it does.

**Comment by petedavis** [comment]
Technically it wont do anything as there is only a single razor IViewEngine in the list, so will do the same as the original code that only ever uses the First() engine in the list. 

Assuming that sometime in the future something like RazorGenerator is implemented for .Net Core, then its view engine could be injected into the list of View Engines. 
https://github.com/RazorGenerator/RazorGenerator/blob/master/RazorGenerator.Mvc/NuGet/Content/App_Start/RazorGeneratorMvcStart.cs.pp

Basic view engine behaviour is they will return null if they cant create a view, this will then try the next view engine in the list.

**Comment by sebastienros** [comment]
That's why I approved, because it was doing nothing ;)

**Pull request merged**
