### PR TITLE
Fix log filename format

### LINKED ISSUE #818: OSX - Logs are not stored at right path
Not sure if this happens in windows but in osx logs are stored in App_Data but with a filename of
App_Data\Logs\file... rather then in a folder.

screen shot 2017-06-12 at 23 42 05

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #818

### CODE REVIEW

**Comment by Jetski5822** [comment]
it fixes the issue because windows is more forgiving, however im not happy that the first two sections are in config.

**Comment by sebastienros** [comment]
We also have "App_Data" in some `.props` file for compilation and publication.

**Comment by jtkech** [comment]
For infos, doing some tests on Ubuntu on Windows 10, what i've seen is that, when msbuild evaluate items, it converts path strings so they use the right platform directory separator.

**Comment by sebastienros** [comment]
@jtkech I think Nick's concern is not that it won't work, but that the same "constant" is defined in many places. This is why I mentioned the ones in pros files too.

But good luck finding a good solution to it. Either by design, or we generate the source files with it injected everywhere ;)

**Comment by jtkech** [comment]
Ah, okay :)

**Pull request merged**
