### PR TITLE
Configuring logging at the application level

### PR DESCRIPTION
**Pull request by sebastienros**
Also reading `logging.json` by default.

### CODE REVIEW

**Comment by Jetski5822** [comment]
So with this will we still be able to add a custom logger from a module?

**Comment by sebastienros** [comment]
I think so, by just resolving the logger factory and adding more loaders. The default one (console) can be disabled by configuration. Yet I am not really keen of that.

**Comment by sebastienros** [comment]
:up: :date:

**Comment by Jetski5822** [comment]
Looks good, mine was a complete hack!

**Comment by PinpointTownes** [comment]
@sebastienros nit: when you push massive changes like this one, that would be great if you could also rebase the `oauth2` branch so I don't spend too much time trying to understand how to fix the merge conflicts caused by your code changes :sweat_smile:

**Comment by sebastienros** [comment]
@PinpointTownes that why you should have merged this branch already ;)

**Comment by PinpointTownes** [comment]
@sebastienros there are still a few things to do, but okay, let's merge the `oauth2` into `master` :smile: 

Note that I'm still facing this weird issue when rebasing `oauth2` on top of `master` (or when directly playing with the `master` bits):

```
Orchard.OrchardException: Shape type Layout not found
   at Orchard.DisplayManagement.Implementation.DisplayHelper.TryInvoke(InvokeBinder binder, Object[] args, Object& result) in C:\Users\Chalet Kévin\Documents\GitHub\Orchard2\src\Orchard.DisplayManagement\Implementation\DisplayHelper.cs:line 40
   at CallSite.Target(Closure , CallSite , Object , Object )
   at CallSite.Target(Closure , CallSite , Object , Object )
   at Orchard.DisplayManagement.Razor.RazorPage`1.Display(Object shape) in C:\Users\Chalet Kévin\Documents\GitHub\Orchard2\src\Orchard.DisplayManagement\Razor\RazorPage.cs:line 76
   at CallSite.Target(Closure , CallSite , _Views_Shared__Layout_cshtml , Object )
   at AspNetCore._Views_Shared__Layout_cshtml.<ExecuteAsync>d__21.MoveNext() in /Views/Shared/_Layout.cshtml:line 7
```

Any idea?

**Comment by stevetayloruk** [comment]
I'm getting this error too when switching themes.

**Comment by jtkech** [comment]
Just tried with the last master, seems to work. To repro i needed to rename / delete the `Layout.cshtml` file of the selected theme.

Did you use a custom theme and / or without a `Layout.cshtml` file?

If you use a custom theme, at least you need a `PlaceHolder.cs` file and a `project.json` file, this to be compiled and loaded. For testing, with minor changes i could use a `lightweight` theme extension without any assembly, but right now you need this.

And you need to enable this custom theme. Oh, just remembered that you can't because **right now you can only enable / disable new modules, not new themes**. You could do it if you alow the `Orchard.Modules` to display all extensions, not only modules. I've tried it, it works.

So, right now you can only select the themes that are already there, `TheTheme` and `SafeMode`. For the admin there is only `TheAdmin`.

Best.

**Comment by stevetayloruk** [comment]
Yeah, I thought now that there was a UI for the themes that it was automatically enabling the theme when changed, but it doesn't. I needed to enable it directly in the DB.

thanks

**Pull request merged**
