### PR TITLE
New admin menu

### PR DESCRIPTION
**Pull request by sebastienros**
This one follows the design guidelines we defined for the admin theme in O1.
It also collapses on small devices and show a fly-out menu.
I don't want to do more things on it before we can have more actual usage and feedback
- We could have the container items be clickable if the chevron was driving the expansion
- It could be converted to a client side rendering and integrate dynamic elements (content tree)

### CODE REVIEW

**Comment by agriffard** [comment]
In Bootstrap 4, it seems the use of FlexBox will be by default : https://github.com/twbs/bootstrap/pull/21389

**Comment by agriffard** [comment]
For the dropdown icon, please use chevron down when collapsed and chevron up when expanded?

**Comment by agriffard** [comment]
Add a different background for sub level and a padding to align vertically a sub link on the parent link.

**Comment by agriffard** [comment]
Use https://github.com/jamesflorentino/nanoScrollerJS to have a thin scrollbar for the menu when it is too long.

**Comment by agriffard** [comment]
Suggestion:
Always show a burger icon (different of the one used to display the fly out menu on small screens).
Place it on the left, before the title.
If you click on it, only the icons will be displayed, not the labels.
In that mode, display the labels over the content: on mouse hover for desktop screens and onclick for tablets.

**Comment by sebastienros** [comment]
I will create an issue with the suggestions, I want to have a discussion first about the changes.

**Pull request merged**
