### PR TITLE
Start working on handlebars.

### PR DESCRIPTION
**Pull request by jtkech**
Just to show where i am.

- First, because a shape is cached and uses a delegate which invokes `RenderAsync()` of a binding strategy object instance which has a scoped lifetime, the shape holds a reference on this object.

    So, here i've used a delegate which invokes a static method which resolves, through the `displayContext.ServiceProvider`, the right service instance to render the shape.

    **Note: if we don't use this PR, maybe still good to apply this change to O2, maybe also to O1**.

- For an Handlebars template context we use a composite of the following objects, an htmlHelper, an urlHelper, the displayContext and the Model / Shape.

- One problem was that inside e.g the `#each` block, the context is changed to the element we are iterating. So, i've made a custom `#foreach` block to inherit the above objects from the parent context.

So, i could use the following.

    <nav>
        <ul class="nav navbar-nav">
            {{#foreach Model.Items}}
                {{Display}}
            {{/foreach}}
        </ul>
    </nav>

    <h1>{{Model.Title}} - {{Model.ContentItem.Author}}</h1>

    {{{Model.Body}}}
    {{HtmlRaw Model.Body}} // idem
    <h3>{{Model.Metadata.DisplayType}}</h3>
    {{HtmlActionLink "Preview the item" "Preview" class="btn btn-default" role="button"}}
    <h3>{{UrlContent "~/page1"}}</h3>
    {{UrlAction "Display" "Item" area="Orchard.Contents" ContentItemId=Model.BodyPart...

Which renders the following.

handlebars

Best.

### CODE REVIEW

**Comment by jtkech** [comment]
So, in `TheTheme`, i could override all razor views with handlebars views. Here the demo home page with some handlebars code snippets. It was interesting to do, as you was asking to me, but not sure it is useful.

handlebars2

I still have a little problem in `ShapeTemplateBindingStrategy`, which has a scoped lifetime, to inject an `IEnumerable<IShapeTemplateViewEngine>`. If the 2 view engines are registered with a scoped lifetime it works, but if they are registered as singletons (as we want), i get a collection of 2 elements but with the same implementation type. Note: it also works if `ShapeTemplateBindingStrategy` is itself a singleton.

 I will try to fix this (but maybe normal), right now the temporary workaround i found is to use `GetServices()` in the constructor of `ShapeTemplateBindingStrategy`.

**Comment by jtkech** [comment]
I fixed the issue when injecting an IEnumerable of view engines registered as singletons at the app level (see above for more details).

This in another PR, see #587. So here, right now i keep the same workaround.

Best.

**Comment by jtkech** [comment]
So, here i tried to see what we can do with handlebars helpers. But not reasonable to reproduce one by one what we can do with razor.

So, we have to define what we need to implement in the context of Handlebars (or another framework) templates, and the ability to write such templates though the admin UI.

Best.

**Comment by stevetayloruk** [comment]
Sorry for being a bit late to the party. Why are we looking to use handlebars?

**Comment by jtkech** [comment]
If i remember correctly what @sebastienros said to me, it's about security issues because with razor files, potentialy, you can do everything. So, the idea would be to have razor views in protected folders and Handlebars templates in public folders / database.

Best.

**Comment by hishamco** [comment]
Seems [Fluid](http://github.com/sebastienros/fluid) is promising, it will be great alternative for handlebars

**Comment by sebastienros** [comment]
@hishamco good eye, we have already removed handlebars and replaced it with fluid, in the Media branch.

**Comment by jtkech** [comment]
Was useful to keep it while working on Fluid, no more needed.

**Pull request closed without merging**
