### PR TITLE
#68: Be able to start up from visual studio

### LINKED ISSUE #68: Be able to start up from visual studio
Just began with Orchard2, so, here it's just to show you what I did to make it working... Maybe it can give you an idea to do it in a better way...

To solve the issue seen in `ExtensionAssemblyLoader`, In `ModuleLoaderContext.cs` at the beginning of the constructor I've added this.

            Project.DefaultCompiler = Project.DefaultRuntimeCompiler;

This way, the `LibraryExporter` uses the right compiler.

But still an issue when compiling a view because in the `DefaultRoslynCompilationService` singleton, a `LibraryExporter` is resolved in the constructor (maybe too early related to my first update). So, in this class, at the beginning of the `GetApplicationReferences()` method, I've added this.

            Project project;
            var libraryExporter = _libraryExporter;
            if (Project.TryGetProject(_environment.ApplicationBasePath, out project))
            {
                var engine = new CompilationEngine(new CompilationEngineContext(
                        _environment,
                        _runtimeEnvironment, // new service resolved in the constructor
                        _loader,
                        new CompilationCache()));

                libraryExporter = engine.CreateProjectExporter(
                    project, _environment.RuntimeFramework, _environment.Configuration);
            }

Then, afterwards I use `libraryExporter` in place of `_libraryExporter`...

Note: In Visual Studio, Orchard.Web is set as the Startup project, and the `web` command is selected.

Best

### PR DESCRIPTION
**Pull request by jtkech**
Fixes #68

Not sure we can do this but it's the only way I've found to start the app from visual studio and get the setup screen (not tested further)...

Best

### CODE REVIEW

**Comment by GVX111** [comment]
<pre> var engine = new CompilationEngine(
                new CompilationEngineContext(
                    _environment,
                    _runtimeEnvironment,
                    _loader,
                    new CompilationCache()));

            var libraryExporter = engine.CreateProjectExporter(
                project, _environment.RuntimeFramework, _environment.Configuration);</pre>
with this code page load need 200ms more than without this..You can change it with expression of if debug mode than you this CreateProjectExporter else use _libraryexporter.

**Comment by GVX111** [comment]
<pre>
 ILibraryExporter libraryExporter;
            if (_hostingEnvironment.IsDevelopment())
            {
                Project project;
                if (!Project.TryGetProject(_environment.ApplicationBasePath, out project))
                    return references;

                var engine = new CompilationEngine(
                    new CompilationEngineContext(
                        _environment,
                        _runtimeEnvironment,
                        _loader,
                        new CompilationCache()));
                libraryExporter = engine.CreateProjectExporter(
                    project, _environment.RuntimeFramework, _environment.Configuration);
            }
            else
            {
                libraryExporter = _libraryExporter;
            }
</pre>
in constructor add IHostingEnvironment with variable _hostingEnvironment

**Comment by sebastienros** [comment]
where is `_libraryExporter` coming from ?

**Comment by GVX111** [comment]
from custructor

**Comment by sebastienros** [comment]
Got it, thanks

**Comment by sebastienros** [comment]
Added

**Pull request merged**
